webtalk_init -webtalk_dir /home/dimitris/di_vhdl/minimum_ones/minimum_ones.sim/sim_1/synth/timing/xsim/xsim.dir/top_module_tb_time_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Feb 25 18:28:21 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6cf1f9af-0750-4246-8a7c-6de5e7cf24ef" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "431416b4d0da497bbbca31e5fd28050d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 1800X Eight-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3486.014 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "450 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "116884_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2948000295 -regid "" -xml /home/dimitris/di_vhdl/minimum_ones/minimum_ones.sim/sim_1/synth/timing/xsim/xsim.dir/top_module_tb_time_synth/webtalk/usage_statistics_ext_xsim.xml -html /home/dimitris/di_vhdl/minimum_ones/minimum_ones.sim/sim_1/synth/timing/xsim/xsim.dir/top_module_tb_time_synth/webtalk/usage_statistics_ext_xsim.html -wdm /home/dimitris/di_vhdl/minimum_ones/minimum_ones.sim/sim_1/synth/timing/xsim/xsim.dir/top_module_tb_time_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
