#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Mar 05 16:41:42 EET 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto ee3b1b05fbca4ce691920a78f65c9fc8 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot InstrDec_tb_behav xil_defaultlib.InstrDec_tb -log elaborate.log"
xelab -wto ee3b1b05fbca4ce691920a78f65c9fc8 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot InstrDec_tb_behav xil_defaultlib.InstrDec_tb -log elaborate.log

