#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Dec 02 13:59:53 EET 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 07e01a9294fb45d7b90d07b9239a8059 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot DSD_Lab2_tb_w_behav xil_defaultlib.DSD_Lab2_tb_w -log elaborate.log"
xelab -wto 07e01a9294fb45d7b90d07b9239a8059 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot DSD_Lab2_tb_w_behav xil_defaultlib.DSD_Lab2_tb_w -log elaborate.log

