#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Dec 02 14:49:35 EET 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim DSD_Lab2_tb_w_time_synth -key {Post-Synthesis:sim_1:Timing:DSD_Lab2_tb_w} -tclbatch DSD_Lab2_tb_w.tcl -log simulate.log"
xsim DSD_Lab2_tb_w_time_synth -key {Post-Synthesis:sim_1:Timing:DSD_Lab2_tb_w} -tclbatch DSD_Lab2_tb_w.tcl -log simulate.log

