#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Mar 05 18:16:12 EET 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 48e737c640a3485ebcd26f368bf23286 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot InstrDec_tb_behav xil_defaultlib.InstrDec_tb -log elaborate.log"
xelab -wto 48e737c640a3485ebcd26f368bf23286 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot InstrDec_tb_behav xil_defaultlib.InstrDec_tb -log elaborate.log

