#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Mar 05 18:16:14 EET 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim InstrDec_tb_behav -key {Behavioral:sim_1:Functional:InstrDec_tb} -tclbatch InstrDec_tb.tcl -view /home/dimitris/di_vhdl/simple_arm/InstrDec_tb_behav.wcfg -log simulate.log"
xsim InstrDec_tb_behav -key {Behavioral:sim_1:Functional:InstrDec_tb} -tclbatch InstrDec_tb.tcl -view /home/dimitris/di_vhdl/simple_arm/InstrDec_tb_behav.wcfg -log simulate.log

