webtalk_init -webtalk_dir /home/dimitris/mealy_seq_det/mealy_seq_det.sim/sim_1/behav/xsim/xsim.dir/mealy_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Feb 11 19:45:42 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6cf1f9af-0750-4246-8a7c-6de5e7cf24ef" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ae8e5c253e9b4db0be37f8863a38efbc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 1800X Eight-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3616.489 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115304_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2144037134 -regid "" -xml /home/dimitris/mealy_seq_det/mealy_seq_det.sim/sim_1/behav/xsim/xsim.dir/mealy_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/dimitris/mealy_seq_det/mealy_seq_det.sim/sim_1/behav/xsim/xsim.dir/mealy_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/dimitris/mealy_seq_det/mealy_seq_det.sim/sim_1/behav/xsim/xsim.dir/mealy_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
